### ISSUE TITLE
파일 사이즈 비교 기술 조사

### ISSUE THREAD

**Issue by gunu9441** [bnk159hair/Project2#2]
파일 사이즈를 비교 할 때 stat 구조체 안에 존재하는 st_size를 사용할 것이며 아래에 보시는 코드는 stat 구조체 형태 입니다.
```c
struct stat {
     //...
     off_t             st_size;   
     //...
}
```

위의 코드에서 볼 수 있는 것 처럼 st_size는 off_t 자료형을 가지고 있고 파일의 크기를 byte 단위로 저장하게 됩니다.

**Comment by bnk159hair** [comment]
좋아요~~

**Comment by rkdehdgns1230** [comment]
좋습니다! 잘 적용해주세요~~~~~

**Comment by BaekSeungGeon** [comment]
수고가 많습니다~~
