### ISSUE TITLE
파일 블락 수 비교 기술 조사

### ISSUE THREAD

**Issue by gunu9441** [bnk159hair/Project2#3]
파일 블락 수 비교 기능을 수행할 때는 stat 구조체 안에 존재하는 st_blocks를 사용합니다. 아래 코드는 stat구조체의 형태 입니다.
```c
struct stat {
     //...
     blkcnt_t       st_blocks; 
     //...
};
```
위의 코드에서 볼 수 있듯이 st_blocks는 blokcnt_t 자료형으로 파일에 할당된 블락의 갯수를 갖고 있습니다.

**Comment by bnk159hair** [comment]
아주 좋아요~~

**Comment by rkdehdgns1230** [comment]
넵 좋습니다!

**Comment by BaekSeungGeon** [comment]
조아요~~

**Comment by gunu9441** [comment]
감사합니다:)
