### ISSUE TITLE
월/일 날짜를 비교하는 기술 조사

### ISSUE THREAD

**Issue by bnk159hair** [bnk159hair/Project2#4]
두 개의 파일을 가져와 월/일일 비교한다.
두 개의 파일 중 어느 날이 더 이른지 출력하고 두 파일의 월/일 이 같다면 같다고 출력한다.
이 때 사용하는 함수는 localtime함수를 사용하여 tm구조체에서 year, mon, day를 가져올 수 있다.

**Comment by BaekSeungGeon** [comment]
수고하셨어요~

**Comment by rkdehdgns1230** [comment]
좋습니다! 좋아요~

**Comment by gunu9441** [comment]
좋습니다~!
